### ISSUE TITLE
Error when executing repair.py

### ISSUE THREAD

**Issue by DietrichXD** [phuze/windows-10-missing-search-icons#9]
Hi, I'm getting this error when executing and I am not sure what I am doing wrong. Thanks for the help!

fetching username...
copying files...
Traceback (most recent call last):
  File "C:\Users\Dietr\Downloads\windows-10-missing-search-icons-master\repair\repair.py", line 90, in <module>
    main()
  File "C:\Users\Dietr\Downloads\windows-10-missing-search-icons-master\repair\repair.py", line 40, in main
    copyDirectory(iconCache, rawStore)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\distutils\dir_util.py", line 123, in copy_tree
    raise DistutilsFileError(
distutils.errors.DistutilsFileError: cannot copy tree 'C:\Users\Dietr\AppData\Local\Packages\Microsoft.Windows.Search_cw5n1h2txyewy\LocalState\AppIconCache\100': not a directory
PS C:\Users\Dietr\Downloads\windows-10-missing-search-icons-master\repair>

**Comment by EdoardoTosin** [comment]
Check the folder name inside `%LocalAppData%\Packages\Microsoft.Windows.Search_cw5n1h2txyewy\LocalState\AppIconCache` and replace line 24 of `repair.py` with the correct one. Example:
from the original
- `iconCache = 'C:\\Users\\'+username+'\\AppData\\Local\\Packages\\'+appName+'\\LocalState\\AppIconCache\\100'`

to  (if my folder is called `125`)

- `iconCache = 'C:\\Users\\'+username+'\\AppData\\Local\\Packages\\'+appName+'\\LocalState\\AppIconCache\\125'`

This should fix the execution error.

**Comment by DietrichXD** [comment]
Thanks, the script now runs. But it doesn't fix anything unfortunately. 
It says some icons are broken, but they don't get fixed. I don't understand why Drive Filestream just doesn't fix this...

**Comment by EdoardoTosin** [comment]
Same. I had to manually replace all corrupted icons with the one found in `C:\Program Files\WindowsApps` of the corresponding app.
